<script>
$('catalog_category_products_table').down('tbody').setAttribute('id', 'catalog_category_products_table_tbody');
var listId = 'catalog_category_products_table_tbody';
var listTag = 'tr';
var ajaxUrl = '<?php echo $this->getUrl('*/categoryProductSortBackend/ajaxBlock', array('_current' => true)) ?>';
var categoryId = '<?php echo $this->getRequest()->getParam('id'); ?>';
var isLimitApplied = '<?php echo $this->getRequest()->getParam('limit'); ?>';
if(categoryId && isLimitApplied == '0') {
  resetListItems(listId, listTag);
  processSorting(categoryId, listId, listTag, ajaxUrl);
}
function batchSort() {
  var i = 0;
  catalog_category_productsJsObject.rows.each(function(row){
    i++;
    var position = $(row).getElementsByClassName('input-text')[0];
    position.value = i;
    position.triggerEvent('keyup');
  });
}
</script>